version: '2'

networks:
  whoseturn-kafka-net:
    driver: bridge

services:
  whoseturn-kafka-zookeeper:
    image: bitnami/zookeeper
    networks:
      - whoseturn-kafka-net
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  whoseturn-kafka:
    image: bitnami/kafka
    networks:
      - whoseturn-kafka-net
    ports:
      - 9092-9095:9092
    depends_on:
      - whoseturn-kafka-zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DELETE_TOPIC_ENABLE= true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=whoseturn-kafka-zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9095-9098